package com.nemonotfound.nemosmossyblocks.datagen;

import net.fabricmc.fabric.api.datagen.v1.FabricDataOutput;
import net.fabricmc.fabric.api.datagen.v1.provider.FabricTagProvider;
import net.minecraft.registry.RegistryWrapper;
import net.minecraft.registry.tag.BlockTags;

import java.util.concurrent.CompletableFuture;

import static com.nemonotfound.nemosmossyblocks.block.ModBlocks.*;

public class BlockTagProvider extends FabricTagProvider.BlockTagProvider {

    public BlockTagProvider(FabricDataOutput output, CompletableFuture<RegistryWrapper.WrapperLookup> registriesFuture) {
        super(output, registriesFuture);
    }

    @Override
    protected void configure(RegistryWrapper.WrapperLookup arg) {
        getOrCreateTagBuilder(BlockTags.AXE_MINEABLE)
                .add(MOSSY_ACACIA_PLANKS)
                .add(MOSSY_ACACIA_STAIRS)
                .add(MOSSY_ACACIA_SLAB)
                .add(MOSSY_ACACIA_PRESSURE_PLATE)
                .add(MOSSY_ACACIA_BUTTON)
                .add(MOSSY_ACACIA_FENCE)
                .add(MOSSY_ACACIA_FENCE_GATE)
                .add(MOSSY_BAMBOO_PLANKS)
                .add(MOSSY_BAMBOO_MOSAIC)
                .add(MOSSY_BAMBOO_STAIRS)
                .add(MOSSY_BAMBOO_MOSAIC_STAIRS)
                .add(MOSSY_BAMBOO_SLAB)
                .add(MOSSY_BAMBOO_MOSAIC_SLAB)
                .add(MOSSY_BAMBOO_PRESSURE_PLATE)
                .add(MOSSY_BAMBOO_BUTTON)
                .add(MOSSY_BAMBOO_FENCE)
                .add(MOSSY_BAMBOO_FENCE_GATE)
                .add(MOSSY_BIRCH_PLANKS)
                .add(MOSSY_BIRCH_STAIRS)
                .add(MOSSY_BIRCH_SLAB)
                .add(MOSSY_BIRCH_PRESSURE_PLATE)
                .add(MOSSY_BIRCH_BUTTON)
                .add(MOSSY_BIRCH_FENCE)
                .add(MOSSY_BIRCH_FENCE_GATE)
                .add(MOSSY_CHERRY_PLANKS)
                .add(MOSSY_CHERRY_STAIRS)
                .add(MOSSY_CHERRY_SLAB)
                .add(MOSSY_CHERRY_PRESSURE_PLATE)
                .add(MOSSY_CHERRY_BUTTON)
                .add(MOSSY_CHERRY_FENCE)
                .add(MOSSY_CHERRY_FENCE_GATE)
                .add(MOSSY_CRIMSON_PLANKS)
                .add(MOSSY_CRIMSON_STAIRS)
                .add(MOSSY_CRIMSON_SLAB)
                .add(MOSSY_CRIMSON_PRESSURE_PLATE)
                .add(MOSSY_CRIMSON_BUTTON)
                .add(MOSSY_CRIMSON_FENCE)
                .add(MOSSY_CRIMSON_FENCE_GATE)
                .add(MOSSY_DARK_OAK_PLANKS)
                .add(MOSSY_DARK_OAK_STAIRS)
                .add(MOSSY_DARK_OAK_SLAB)
                .add(MOSSY_DARK_OAK_PRESSURE_PLATE)
                .add(MOSSY_DARK_OAK_BUTTON)
                .add(MOSSY_DARK_OAK_FENCE)
                .add(MOSSY_DARK_OAK_FENCE_GATE)
                .add(MOSSY_JUNGLE_PLANKS)
                .add(MOSSY_JUNGLE_STAIRS)
                .add(MOSSY_JUNGLE_SLAB)
                .add(MOSSY_JUNGLE_PRESSURE_PLATE)
                .add(MOSSY_JUNGLE_BUTTON)
                .add(MOSSY_JUNGLE_FENCE)
                .add(MOSSY_JUNGLE_FENCE_GATE)
                .add(MOSSY_MANGROVE_PLANKS)
                .add(MOSSY_MANGROVE_STAIRS)
                .add(MOSSY_MANGROVE_SLAB)
                .add(MOSSY_MANGROVE_PRESSURE_PLATE)
                .add(MOSSY_MANGROVE_BUTTON)
                .add(MOSSY_MANGROVE_FENCE)
                .add(MOSSY_MANGROVE_FENCE_GATE)
                .add(MOSSY_OAK_PLANKS)
                .add(MOSSY_OAK_STAIRS)
                .add(MOSSY_OAK_SLAB)
                .add(MOSSY_OAK_PRESSURE_PLATE)
                .add(MOSSY_OAK_BUTTON)
                .add(MOSSY_OAK_FENCE)
                .add(MOSSY_OAK_FENCE_GATE)
                .add(MOSSY_SPRUCE_PLANKS)
                .add(MOSSY_SPRUCE_STAIRS)
                .add(MOSSY_SPRUCE_SLAB)
                .add(MOSSY_SPRUCE_PRESSURE_PLATE)
                .add(MOSSY_SPRUCE_BUTTON)
                .add(MOSSY_SPRUCE_FENCE)
                .add(MOSSY_SPRUCE_FENCE_GATE)
                .add(MOSSY_WARPED_PLANKS)
                .add(MOSSY_WARPED_STAIRS)
                .add(MOSSY_WARPED_SLAB)
                .add(MOSSY_WARPED_PRESSURE_PLATE)
                .add(MOSSY_WARPED_BUTTON)
                .add(MOSSY_WARPED_FENCE)
                .add(MOSSY_WARPED_FENCE_GATE)
                .add(MOSSY_ACACIA_LOG)
                .add(MOSSY_BAMBOO_BLOCK)
                .add(MOSSY_BIRCH_LOG)
                .add(MOSSY_CHERRY_LOG)
                .add(MOSSY_CRIMSON_STEM)
                .add(MOSSY_DARK_OAK_LOG)
                .add(MOSSY_JUNGLE_LOG)
                .add(MOSSY_MANGROVE_LOG)
                .add(MOSSY_OAK_LOG)
                .add(MOSSY_SPRUCE_LOG)
                .add(MOSSY_WARPED_STEM)
                .add(MOSSY_ACACIA_WOOD)
                .add(MOSSY_BIRCH_WOOD)
                .add(MOSSY_CHERRY_WOOD)
                .add(MOSSY_CRIMSON_HYPHAE)
                .add(MOSSY_DARK_OAK_WOOD)
                .add(MOSSY_JUNGLE_WOOD)
                .add(MOSSY_MANGROVE_WOOD)
                .add(MOSSY_OAK_WOOD)
                .add(MOSSY_SPRUCE_WOOD)
                .add(MOSSY_WARPED_HYPHAE)
                .add(MOSSY_OAK_DOOR)
                .add(MOSSY_SPRUCE_DOOR)
                .add(MOSSY_BIRCH_DOOR)
                .add(MOSSY_ACACIA_DOOR)
                .add(MOSSY_DARK_OAK_DOOR)
                .add(MOSSY_MANGROVE_DOOR)
                .add(MOSSY_CHERRY_DOOR)
                .add(MOSSY_BAMBOO_DOOR)
                .add(MOSSY_JUNGLE_DOOR)
                .add(MOSSY_CRIMSON_DOOR)
                .add(MOSSY_WARPED_DOOR)
                .add(MOSSY_OAK_TRAPDOOR)
                .add(MOSSY_SPRUCE_TRAPDOOR)
                .add(MOSSY_BIRCH_TRAPDOOR)
                .add(MOSSY_ACACIA_TRAPDOOR)
                .add(MOSSY_DARK_OAK_TRAPDOOR)
                .add(MOSSY_MANGROVE_TRAPDOOR)
                .add(MOSSY_CHERRY_TRAPDOOR)
                .add(MOSSY_BAMBOO_TRAPDOOR)
                .add(MOSSY_JUNGLE_TRAPDOOR)
                .add(MOSSY_CRIMSON_TRAPDOOR)
                .add(MOSSY_WARPED_TRAPDOOR);

        getOrCreateTagBuilder(BlockTags.PICKAXE_MINEABLE)
                .add(MOSSY_STONE)
                .add(MOSSY_STONE_STAIRS)
                .add(MOSSY_STONE_SLAB)
                .add(MOSSY_STONE_PRESSURE_PLATE)
                .add(MOSSY_STONE_BUTTON)
                .add(MOSSY_IRON_BARS)
                .add(MOSSY_CHISELED_STONE_BRICKS)
                .add(INFESTED_MOSSY_CHISELED_STONE_BRICKS)
                .add(MOSSY_BRICKS)
                .add(MOSSY_BRICK_SLAB)
                .add(MOSSY_BRICK_STAIRS)
                .add(MOSSY_BRICK_WALL)
                .add(MOSSY_IRON_DOOR)
                .add(MOSSY_DEEPSLATE)
                .add(MOSSY_COBBLED_DEEPSLATE)
                .add(MOSSY_COBBLED_DEEPSLATE_STAIRS)
                .add(MOSSY_COBBLED_DEEPSLATE_SLAB)
                .add(MOSSY_COBBLED_DEEPSLATE_WALL)
                .add(MOSSY_DEEPSLATE_BRICKS)
                .add(MOSSY_DEEPSLATE_BRICK_STAIRS)
                .add(MOSSY_DEEPSLATE_BRICK_SLAB)
                .add(MOSSY_DEEPSLATE_BRICK_WALL)
                .add(MOSSY_DEEPSLATE_TILES)
                .add(MOSSY_DEEPSLATE_TILE_STAIRS)
                .add(MOSSY_DEEPSLATE_TILE_SLAB)
                .add(MOSSY_DEEPSLATE_TILE_WALL)
                .add(MOSSY_TUFF);

        getOrCreateTagBuilder(BlockTags.WOODEN_FENCES)
                .add(MOSSY_ACACIA_FENCE)
                .add(MOSSY_BAMBOO_FENCE)
                .add(MOSSY_BIRCH_FENCE)
                .add(MOSSY_CHERRY_FENCE)
                .add(MOSSY_CRIMSON_FENCE)
                .add(MOSSY_DARK_OAK_FENCE)
                .add(MOSSY_JUNGLE_FENCE)
                .add(MOSSY_MANGROVE_FENCE)
                .add(MOSSY_OAK_FENCE)
                .add(MOSSY_SPRUCE_FENCE)
                .add(MOSSY_WARPED_FENCE);

        getOrCreateTagBuilder(BlockTags.WALLS)
                .add(MOSSY_BRICK_WALL)
                .add(MOSSY_COBBLED_DEEPSLATE_WALL)
                .add(MOSSY_DEEPSLATE_BRICK_WALL)
                .add(MOSSY_DEEPSLATE_TILE_WALL);
    }
}
